name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs once per day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SoujanyaS257
          outputs: dist/snake.svg
          background: "#000000"    # 🖤 Always black background
          snake_color: "#39FF14"   # 💚 Neon green snake (you can change)
          color_dots: "#222222,#444444,#666666,#888888"  # dark gray dots

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
